<a href="https://colab.research.google.com/github/rekuantsun/PTDL-Python/blob/main/Numpy_4_Thao_tac_voi_vector_va_ma_tran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1

In [1]:
import numpy as np
a =np.arange(1,8)
print(a)
print("so chieu cua vector a: ",a.ndim)
print("so chieu cua vector chuyen vi vector a: ",a.T.ndim)
print("kich thuoc cua vector a: ",a.shape)
print("kich thuoc cua vector a chuyen vivector a: ",a.T.shape)

[1 2 3 4 5 6 7]
so chieu cua vector a:  1
so chieu cua vector chuyen vi vector a:  1
kich thuoc cua vector a:  (7,)
kich thuoc cua vector a chuyen vivector a:  (7,)


In [2]:
b=np.linspace(0,6,7)
print(b)
print("so chieu cua vector b: ",b.ndim)
print("so chieu cua vector chuyen vi vector b: ",b.T.ndim)
print("kich thuoc cua vector b : ",b.shape)
print("kich thuoc cua vector chuyen vi vector b: ",b.T.shape)

[0. 1. 2. 3. 4. 5. 6.]
so chieu cua vector b:  1
so chieu cua vector chuyen vi vector b:  1
kich thuoc cua vector b :  (7,)
kich thuoc cua vector chuyen vi vector b:  (7,)


In [3]:
c=np.logspace(1,7,7)
print(c)
print("so chieu cua vector c: ",c.ndim)
print("so chieu cua vector vector chuyen vi vector c: ",c.T.ndim)
print("kich thuoc cua vector c: ",c.shape)
print("kich thuoc cua vector chuyen vi vector c: ",c.T.shape)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07]
so chieu cua vector c:  1
so chieu cua vector vector chuyen vi vector c:  1
kich thuoc cua vector c:  (7,)
kich thuoc cua vector chuyen vi vector c:  (7,)


In [4]:
d=np.random.rand(7)
print(d)
print("so chieu cua vector d: ",d.ndim)
print("so chieu cua vector chuyen vi vector d: ",d.T.ndim)
print("kich thuoc cua vector d: ",d.shape)
print("kich thuoc cua vector chuyen vi vector d: ",d.T.shape)

[0.33366994 0.62202478 0.6770331  0.43918713 0.43840911 0.71986926
 0.73360781]
so chieu cua vector d:  1
so chieu cua vector chuyen vi vector d:  1
kich thuoc cua vector d:  (7,)
kich thuoc cua vector chuyen vi vector d:  (7,)


Bài 2

In [5]:
#ham arange()
import numpy as np
a = np.arange(1,71).reshape(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70]]
so chieu cua ma tran A:  2
so chieu cua ma tran chuyen vi A:  2
so kich thuoc cua ma tran A:  (10, 7)
so kich thuoc cua ma tran chuyen vi A:  (7, 10)


In [6]:
#ham linspace()
a = np.linspace(0,70,num=70).reshape(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[ 0.          1.01449275  2.02898551  3.04347826  4.05797101  5.07246377
   6.08695652]
 [ 7.10144928  8.11594203  9.13043478 10.14492754 11.15942029 12.17391304
  13.1884058 ]
 [14.20289855 15.2173913  16.23188406 17.24637681 18.26086957 19.27536232
  20.28985507]
 [21.30434783 22.31884058 23.33333333 24.34782609 25.36231884 26.37681159
  27.39130435]
 [28.4057971  29.42028986 30.43478261 31.44927536 32.46376812 33.47826087
  34.49275362]
 [35.50724638 36.52173913 37.53623188 38.55072464 39.56521739 40.57971014
  41.5942029 ]
 [42.60869565 43.62318841 44.63768116 45.65217391 46.66666667 47.68115942
  48.69565217]
 [49.71014493 50.72463768 51.73913043 52.75362319 53.76811594 54.7826087
  55.79710145]
 [56.8115942  57.82608696 58.84057971 59.85507246 60.86956522 61.88405797
  62.89855072]
 [63.91304348 64.92753623 65.94202899 66.95652174 67.97101449 68.98550725
  70.        ]]
so chieu cua ma tran A:  2
so chieu cua ma tran chuyen vi A:  2
so kich thuoc cua ma tran A:  (10, 7)
so kich 

In [7]:
#hamlogspace()
a = np.logspace(0,70,num=70).reshape(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[1.00000000e+00 1.03393385e+01 1.06901920e+02 1.10529514e+03
  1.14280206e+04 1.18158173e+05 1.22167735e+06]
 [1.26313356e+07 1.30599655e+08 1.35031404e+09 1.39613539e+10
  1.44351164e+11 1.49249555e+12 1.54314166e+13]
 [1.59550640e+14 1.64964807e+15 1.70562698e+16 1.76350547e+17
  1.82334800e+18 1.88522122e+19 1.94919403e+20]
 [2.01533769e+21 2.08372585e+22 2.15443469e+23 2.22754295e+24
  2.30313206e+25 2.38128619e+26 2.46209240e+27]
 [2.54564067e+28 2.63202406e+29 2.72133877e+30 2.81368427e+31
  2.90916341e+32 3.00788252e+33 3.10995155e+34]
 [3.21548418e+35 3.32459793e+36 3.43741434e+37 3.55405904e+38
  3.67466194e+39 3.79935737e+40 3.92828419e+41]
 [4.06158599e+42 4.19941123e+43 4.34191342e+44 4.48925126e+45
  4.64158883e+46 4.79909581e+47 4.96194760e+48]
 [5.13032558e+49 5.30441728e+50 5.48441658e+51 5.67052394e+52
  5.86294665e+53 6.06189899e+54 6.26760256e+55]
 [6.48028644e+56 6.70018750e+57 6.92755066e+58 7.16262912e+59
  7.40568469e+60 7.65698808e+61 7.91681916e+62]
 [8.185467

In [8]:
#ham random.rand()
a = np.random.rand(10,7)
print(a)
print("so chieu cua ma tran A: ",a.ndim)
print("so chieu cua ma tran chuyen vi A: ",a.T.ndim)
print("so kich thuoc cua ma tran A: ",a.shape)
print("so kich thuoc cua ma tran chuyen vi A: ",a.T.shape)

[[0.89782132 0.18003771 0.31425101 0.88210996 0.02252659 0.56146826
  0.17449176]
 [0.85895216 0.44817506 0.68206542 0.925624   0.63658118 0.88671392
  0.06136695]
 [0.80179604 0.44221236 0.97349062 0.74988135 0.49501451 0.58714739
  0.65815939]
 [0.47528887 0.05283863 0.22569486 0.04354482 0.39188769 0.13195029
  0.61282732]
 [0.21806095 0.6849011  0.97459312 0.72218908 0.83987645 0.78129324
  0.98053262]
 [0.85405693 0.40485164 0.37936238 0.80041891 0.62578809 0.49750854
  0.1818267 ]
 [0.53519878 0.91523704 0.8326369  0.79504907 0.31825884 0.86599177
  0.05272371]
 [0.51485309 0.26632972 0.04649043 0.13039766 0.8528166  0.08309211
  0.28933155]
 [0.39654553 0.8697451  0.69304694 0.88914697 0.65364465 0.82587116
  0.61824713]
 [0.77876485 0.16819734 0.25426788 0.2270892  0.74645249 0.01040916
  0.89260436]]
so chieu cua ma tran A:  2
so chieu cua ma tran chuyen vi A:  2
so kich thuoc cua ma tran A:  (10, 7)
so kich thuoc cua ma tran chuyen vi A:  (7, 10)


Bài 3

In [9]:
#chuyen ma tran o cau 2 thanh vector
a.flatten()

array([0.89782132, 0.18003771, 0.31425101, 0.88210996, 0.02252659,
       0.56146826, 0.17449176, 0.85895216, 0.44817506, 0.68206542,
       0.925624  , 0.63658118, 0.88671392, 0.06136695, 0.80179604,
       0.44221236, 0.97349062, 0.74988135, 0.49501451, 0.58714739,
       0.65815939, 0.47528887, 0.05283863, 0.22569486, 0.04354482,
       0.39188769, 0.13195029, 0.61282732, 0.21806095, 0.6849011 ,
       0.97459312, 0.72218908, 0.83987645, 0.78129324, 0.98053262,
       0.85405693, 0.40485164, 0.37936238, 0.80041891, 0.62578809,
       0.49750854, 0.1818267 , 0.53519878, 0.91523704, 0.8326369 ,
       0.79504907, 0.31825884, 0.86599177, 0.05272371, 0.51485309,
       0.26632972, 0.04649043, 0.13039766, 0.8528166 , 0.08309211,
       0.28933155, 0.39654553, 0.8697451 , 0.69304694, 0.88914697,
       0.65364465, 0.82587116, 0.61824713, 0.77876485, 0.16819734,
       0.25426788, 0.2270892 , 0.74645249, 0.01040916, 0.89260436])

In [10]:
#chuyen vector thanh ma tran
a.reshape(10,7)

array([[0.89782132, 0.18003771, 0.31425101, 0.88210996, 0.02252659,
        0.56146826, 0.17449176],
       [0.85895216, 0.44817506, 0.68206542, 0.925624  , 0.63658118,
        0.88671392, 0.06136695],
       [0.80179604, 0.44221236, 0.97349062, 0.74988135, 0.49501451,
        0.58714739, 0.65815939],
       [0.47528887, 0.05283863, 0.22569486, 0.04354482, 0.39188769,
        0.13195029, 0.61282732],
       [0.21806095, 0.6849011 , 0.97459312, 0.72218908, 0.83987645,
        0.78129324, 0.98053262],
       [0.85405693, 0.40485164, 0.37936238, 0.80041891, 0.62578809,
        0.49750854, 0.1818267 ],
       [0.53519878, 0.91523704, 0.8326369 , 0.79504907, 0.31825884,
        0.86599177, 0.05272371],
       [0.51485309, 0.26632972, 0.04649043, 0.13039766, 0.8528166 ,
        0.08309211, 0.28933155],
       [0.39654553, 0.8697451 , 0.69304694, 0.88914697, 0.65364465,
        0.82587116, 0.61824713],
       [0.77876485, 0.16819734, 0.25426788, 0.2270892 , 0.74645249,
        0.01040916, 0.8

Bài 4

In [11]:
import numpy as np
a = np.logspace(0,150,num=150).reshape(10,15)
print(a)
print("hang thu 3 cua ma tran a: ", a[2:3])
print("cot thu 5 cua ma tran a: ", a[:,4:5])

[[1.00000000e+000 1.01557362e+001 1.03138977e+002 1.04745224e+003
  1.06376485e+004 1.08033152e+005 1.09715619e+006 1.11424288e+007
  1.13159567e+008 1.14921870e+009 1.16711619e+010 1.18529241e+011
  1.20375170e+012 1.22249846e+013 1.24153719e+014]
 [1.26087241e+015 1.28050875e+016 1.30045090e+017 1.32070362e+018
  1.34127175e+019 1.36216020e+020 1.38337396e+021 1.40491810e+022
  1.42679775e+023 1.44901815e+024 1.47158460e+025 1.49450249e+026
  1.51777730e+027 1.54141458e+028 1.56541998e+029]
 [1.58979923e+030 1.61455815e+031 1.63970266e+032 1.66523876e+033
  1.69117254e+034 1.71751022e+035 1.74425806e+036 1.77142246e+037
  1.79900992e+038 1.82702700e+039 1.85548042e+040 1.88437696e+041
  1.91372352e+042 1.94352711e+043 1.97379486e+044]
 [2.00453398e+045 2.03575182e+046 2.06745584e+047 2.09965360e+048
  2.13235280e+049 2.16556124e+050 2.19928686e+051 2.23353771e+052
  2.26832196e+053 2.30364794e+054 2.33952406e+055 2.37595891e+056
  2.41296118e+057 2.45053971e+058 2.48870348e+059]
 [2.

Bài 5

In [12]:
import numpy as np

#Ham tinh gia tri trung binh: np.mean()
x = np.array([1,2,3,4,5])
print("tinh gia tri trung binh: ",np.mean(x))

#Ham tinh gia tri trung vi : np.median()
X = np.array([2, 5, 3, 4,1, 7])
print("tinh gia tri trung vi: ",np.median(X))

#Ham tinh gia tri yeu vi : np.nanmedian()
y = np.array([2, 5, 3, 4,1, 7,np.nan])
print("tinh gia tri yeu vi: ",np.nanmedian(y))

#Ham tinh phuong sai : np.var()
Y = np.array([1,2,4,6,7])
print("tinh phuong sai: ",np.var(Y))

#Ham tinh do lech chuan : np.std()
print("tinh do lech chuan: ", np.std(Y))

tinh gia tri trung binh:  3.0
tinh gia tri trung vi:  3.5
tinh gia tri yeu vi:  3.5
tinh phuong sai:  5.2
tinh do lech chuan:  2.280350850198276


In [13]:
#GT do lech chuan
a = np.arange(1,151).reshape(15,10)
print(a)
print("do lech chuan tung hang cua ma tran a: ",np.std(a,axis=1))
print("do lech chuan tung cot cua ma tran a: ",np.std(a,axis =0))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]]
do lech chuan tung hang cua ma tran a:  [2.87228132 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132
 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132
 2.87228132 2.87228132 2.87228132]
do lech chuan tung cot cua ma tran a:  [43.20493799 43.20493799 43.20493799 43.20493799 43.20493799 43.20493799
 43.20493799 43.20493799 43.20493