<a href="https://colab.research.google.com/github/rekuantsun/PTDL-Python/blob/main/Numpy_3_apply_along_axis().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm này.

numpy. apply_along_axis ( func1d , axis , arr , * args , ** kwargs )

- hàm func1d (M,) -> (Nj…) : Hàm này phải chấp nhận mảng 1-D. Nó được áp dụng cho các lát arr 1-D dọc theo trục được chỉ định.
- axis : số nguyên trục

Trục dọc theo arr được cắt.

- arr :ndarray (Ni…, M, Nk…)

Đầu vào mảng.

- args: bất kỳ

Đối số bổ sung cho func1d .

- kwargs: bất kỳ

câu 2 : Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [1]:
import numpy as np
a = np.random.randint(1,10,[15,17])
a

array([[9, 4, 7, 9, 4, 8, 2, 6, 8, 4, 1, 4, 3, 5, 9, 1, 5],
       [9, 4, 9, 4, 4, 2, 1, 8, 2, 2, 1, 6, 8, 9, 3, 9, 9],
       [3, 1, 8, 4, 5, 1, 9, 2, 9, 2, 6, 9, 6, 1, 5, 3, 9],
       [7, 1, 6, 1, 9, 4, 8, 8, 1, 6, 3, 9, 5, 3, 6, 1, 2],
       [7, 2, 8, 1, 3, 6, 7, 6, 3, 2, 1, 3, 6, 4, 2, 9, 3],
       [1, 2, 8, 8, 7, 9, 4, 3, 7, 6, 2, 8, 6, 8, 5, 5, 1],
       [9, 9, 5, 3, 2, 6, 2, 8, 9, 3, 9, 4, 2, 3, 3, 4, 2],
       [7, 8, 2, 6, 5, 1, 8, 3, 2, 3, 7, 6, 8, 4, 1, 9, 9],
       [8, 2, 5, 6, 3, 4, 5, 2, 8, 8, 7, 7, 1, 5, 7, 1, 1],
       [3, 5, 8, 4, 2, 7, 6, 5, 3, 8, 7, 5, 9, 1, 2, 2, 6],
       [2, 9, 2, 3, 2, 1, 1, 7, 2, 7, 1, 9, 2, 1, 9, 5, 1],
       [1, 9, 9, 7, 6, 8, 4, 1, 6, 2, 3, 9, 8, 6, 5, 1, 7],
       [4, 2, 3, 5, 2, 2, 4, 4, 5, 1, 8, 2, 9, 5, 7, 6, 4],
       [4, 7, 5, 5, 6, 5, 9, 3, 9, 3, 5, 2, 2, 5, 8, 4, 7],
       [6, 8, 8, 1, 6, 4, 7, 8, 6, 5, 3, 4, 1, 6, 4, 7, 7]])

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là 
tim_gia_tri_lon_nhat(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [3]:
def tim_gia_tri_lon_nhat(a):
 return np.max(a)
np.apply_along_axis(tim_gia_tri_lon_nhat,1,a)

array([9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9, 8])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là
tim_gia_tri_nho_nhat(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [2]:
def tim_gia_tri_nho_nhat(a):
  return np.min(a)
np.apply_along_axis(tim_gia_tri_nho_nhat,0,a)

array([1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là 
tinh_tong(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def tinh_tong(a):
  return np.sum(a)
np.apply_along_axis(tinh_tong,1,a)

array([89, 90, 83, 80, 73, 90, 83, 89, 80, 83, 64, 92, 73, 89, 91])