<a href="https://colab.research.google.com/github/rekuantsun/PTDL-Python/blob/main/Numpy_3_apply_along_axis().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm này.

numpy. apply_along_axis ( func1d , axis , arr , * args , ** kwargs )


câu 2 : Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [2]:
import numpy as np
a = np.random.randint(1,10,[15,17])
a

array([[7, 9, 4, 6, 3, 9, 5, 4, 4, 9, 9, 6, 5, 7, 9, 3, 5],
       [2, 2, 8, 5, 3, 3, 5, 7, 9, 6, 8, 7, 3, 5, 2, 4, 6],
       [5, 4, 5, 3, 8, 8, 5, 3, 3, 4, 3, 9, 2, 1, 7, 7, 9],
       [4, 1, 3, 9, 1, 4, 7, 7, 8, 9, 8, 9, 5, 6, 1, 9, 3],
       [7, 2, 7, 4, 1, 6, 4, 2, 7, 6, 3, 6, 9, 2, 4, 4, 2],
       [7, 7, 5, 2, 4, 5, 3, 5, 5, 2, 9, 9, 7, 9, 5, 3, 7],
       [6, 2, 7, 2, 1, 7, 2, 9, 8, 2, 7, 8, 2, 1, 6, 4, 8],
       [9, 5, 2, 3, 1, 6, 7, 6, 9, 2, 5, 5, 3, 2, 8, 2, 6],
       [8, 5, 5, 2, 7, 5, 6, 7, 2, 7, 8, 9, 3, 2, 2, 2, 4],
       [2, 6, 8, 3, 2, 8, 8, 7, 4, 9, 2, 7, 9, 1, 4, 4, 4],
       [5, 7, 4, 3, 3, 7, 9, 5, 6, 9, 9, 8, 3, 8, 8, 2, 9],
       [2, 6, 6, 4, 4, 4, 3, 3, 1, 7, 6, 9, 8, 6, 1, 1, 5],
       [2, 1, 4, 8, 1, 6, 3, 9, 7, 8, 4, 5, 6, 6, 5, 9, 1],
       [6, 2, 6, 9, 4, 9, 8, 2, 7, 3, 3, 3, 3, 6, 3, 3, 2],
       [7, 5, 7, 4, 9, 2, 5, 3, 9, 2, 2, 8, 6, 2, 9, 3, 6]])

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là 
tim_gia_tri_lon_nhat(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [7]:
def max_value(a):
 return np.max(a)
np.apply_along_axis(max_value,1,a)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là
tim_gia_tri_nho_nhat(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [4]:
def min_value(a):
  return np.min(a)
np.apply_along_axis(min_value,0,a)

array([2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 3, 2, 1, 1, 1, 1])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là 
tinh_tong(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [6]:
def tong(a):
  return np.sum(a)
np.apply_along_axis(tong,1,a)

array([104,  85,  86,  94,  76,  94,  82,  81,  84,  88, 105,  76,  85,
        79,  89])