<a href="https://colab.research.google.com/github/rekuantsun/PTDL-Python/blob/main/Numpy_3_apply_along_axis().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm này.

numpy. apply_along_axis ( func1d , axis , arr , * args , ** kwargs )


câu 2 : Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [ ]:
import numpy as np
a = np.random.randint(1,10,[15,17])
a

array([[5, 5, 3, 7, 5, 7, 8, 8, 8, 6, 5, 4, 7, 9, 2, 4, 9],
       [2, 3, 8, 9, 6, 7, 1, 9, 8, 4, 5, 5, 4, 7, 8, 3, 7],
       [9, 1, 2, 5, 8, 4, 2, 3, 3, 3, 8, 2, 7, 1, 4, 3, 4],
       [4, 1, 4, 8, 6, 9, 8, 7, 7, 5, 1, 1, 8, 9, 3, 9, 6],
       [1, 8, 9, 4, 4, 8, 4, 6, 5, 5, 7, 5, 2, 7, 3, 6, 3],
       [4, 6, 8, 1, 1, 4, 9, 6, 8, 6, 1, 1, 6, 8, 4, 3, 2],
       [8, 4, 8, 9, 9, 9, 3, 7, 6, 4, 8, 6, 5, 7, 9, 9, 9],
       [9, 5, 4, 7, 3, 6, 7, 9, 8, 5, 5, 6, 9, 7, 1, 6, 9],
       [4, 2, 5, 7, 3, 6, 4, 3, 1, 5, 3, 3, 8, 3, 5, 4, 3],
       [1, 7, 7, 4, 9, 5, 6, 4, 8, 5, 7, 7, 7, 4, 4, 2, 4],
       [4, 7, 8, 4, 6, 8, 6, 3, 6, 1, 5, 3, 4, 5, 9, 3, 9],
       [1, 9, 6, 8, 3, 1, 1, 6, 3, 6, 5, 2, 2, 5, 1, 8, 8],
       [2, 6, 1, 6, 9, 3, 4, 7, 1, 3, 2, 6, 8, 7, 3, 9, 8],
       [1, 7, 3, 7, 2, 8, 7, 4, 5, 3, 6, 2, 3, 3, 1, 4, 4],
       [4, 7, 3, 8, 7, 1, 9, 1, 6, 8, 6, 3, 5, 4, 3, 6, 5]])

Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là 
tim_gia_tri_lon_nhat(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def max_value(a):
 return np.max(a)
np.apply_along_axis(max_value,1,a)

array([9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 8, 9])

Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là
tim_gia_tri_nho_nhat(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def min_value(a):
  return np.min(a)
np.apply_along_axis(min_value,0,a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2])

Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là 
tinh_tong(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [ ]:
def tong(a):
  return np.sum(a)
np.apply_along_axis(tong,1,a)

array([102,  96,  69,  96,  87,  78, 120, 106,  69,  91,  91,  75,  85,
        70,  86])

Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là 1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [ ]:
def tong2(vector_a):
  sum  = 0
  for i in range(len(vector_a)):
    if (i % 2 != 0):
      sum  = sum +vector_a[i]
  return sum
print("tổng các phần tử có chỉ số lẻ")
print (np.apply_along_axis(tong2, 1, a))

tổng các phần tử có chỉ số lẻ
[50 47 22 49 49 35 55 51 33 38 34 45 47 38 38]
